### ISSUE TITLE
ImportError: cannot import name 'MultiScaleDeformableAttention' from 'mmcv.cnn.bricks.transformer' (/home/hys/anaconda3/envs/SAME/lib/python3.7/site-packages/mmcv/cnn/bricks/transformer.py

### ISSUE THREAD

**Issue by YeSorno919** [alibaba-damo-academy/same#1]
I  had the issue when running your reg_same_affine.py.

Following your requirement.txt  ,my environment is:

torch：1.9.0

torchvision：0.10.0

mmcv-full==1.4.7

mmdet==2.20.0

GPU 0,1: NVIDIA GeForce RTX 4090,

CUDA Version: 12.1

The way I installed mmcv-full on the anaconda virtual environment on the far server is:
pip install mmcv_full-1.4.7-cp37-cp37m-manylinux1_x86_64.whl

I had found many ways to sort this problem ,but it didn't work. 
I am looking forward to your suggestion to fix it?

**Comment by YeSorno919** [comment]
> I had the issue when running your reg_same_affine.py.
> 
> Following your requirement.txt ,my environment is:
> 
> torch：1.9.0
> 
> torchvision：0.10.0
> 
> mmcv-full==1.4.7
> 
> mmdet==2.20.0
> 
> GPU 0,1: NVIDIA GeForce RTX 4090,
> 
> CUDA Version: 12.1
> 
> The way I installed mmcv-full on the anaconda virtual environment on the far server is: pip install mmcv_full-1.4.7-cp37-cp37m-manylinux1_x86_64.whl
> 
> I had found many ways to sort this problem ,but it didn't work. I am looking forward to your suggestion to fix it?

wow ，I had sorted it 。I am sorry to bother you！I originally installed the package directly through PyCharm according to your requirement. txt. Finally, I manually installed all the packages one by one. Perhaps the mmcv-full version of 1.4.7 automatically installed by PyCharm is incorrect. I install mmcv-full through offline wheel installation

**Comment by Alison-brie** [comment]
Sorry for the late reply. It is indeed quite challenging to install the environment for `mmcv-full`, and I'm glad that your issue has been resolved. I have updated the readme and added the installation steps for `mmcv-full`, which are provided for reference.
