### ISSUE TITLE
SAM checkpoint

### ISSUE THREAD

**Issue by MohammedSB** [alibaba-damo-academy/same#2]
Hi,

Where is the checkpoint used in:
https://github.com/alibaba-damo-academy/same/blob/859321c478bde29aa46be443138c08dbdce2df8d/scripts/train_config/train_config_abdomen_wSAMLoss.py#L22C9-L22C52

I can use the SAM.pth or SAMv2_iter_20000.pth checkpoint instead, right?

**Comment by Alison-brie** [comment]
Yes, you can use the model weight provided in SAM Repo. I recommend using SAM.pth.
