### ISSUE TITLE
How to obtain masks?

### ISSUE THREAD

**Issue by MohammedSB** [alibaba-damo-academy/same#3]
Hi,

I can't remember reading this from the paper, but what is `case1_mask.nii.gz` and `case1_label.nii.gz`?

Edit: ok the masks are the body masks right?
Is there code to obtain that?

**Comment by Alison-brie** [comment]
Hi,

*_label.nii.gz refers to the segmentation label corresponding to the case, typically used to evaluate registration performance during the testing phase (by calculating the Dice score before and after registration). This data is generally annotated by radiologists and obtained through collaboration with hospitals or released from public datasets.

*_mask.nii.gz corresponds to the contour mask for the case, which is generated through an algorithm during data preprocessing (using the seg_bg_mask function from the GitHub repository by 'from SAMReg.tools.utils.med import seg_bg_mask').
